@startuml
left to right direction

entity "Студент" as student {
  name: varchar
  has_eaten: boolean
  is_late: boolean
  exam_passed: boolean
  grade: varchar
  cheat_sheet_made: boolean
  game_won_with_professor: boolean
  bonus_points: int
  slept_well: boolean
}

entity "Предмет" as item {
  name: varchar
  description: text
  exam_bonus: int
  is_cheatsheet: boolean
  is_notebook_with_notes: boolean
  used: boolean
}

entity "Инвентарь" as inventory {
  student_id: int [FK]
  item_id: int [FK]
  получен_в_сцене: varchar
}

entity "Сцена" as scene {
  название: varchar
  описание: text
}

entity "Результат игры" as result {
  student_id: int [FK]
  дата_игры: datetime
  исход: varchar
  оценка: varchar
  причина: text
}

entity "Сохранение" as save {
  student_id: int [FK]
  current_scene: varchar
  дата_сохранения: datetime
}

' Связи
student ||--o{ inventory : "имеет"
item ||--o{ inventory : "включает"

student ||--o{ result : "получает"
student ||--o{ save : "сохраняется"

scene ||--o{ save : "текущая"


@enduml
